### ISSUE TITLE
Awaiting bar

### ISSUE THREAD

**Issue by ghost** [Fredi/IRCClient#12]
Hey Fredi, nice work!

I was wondering if you've tried adding an 'awaiting' input bar. Something like this: "nick> command here". Similar to mysqlclient, perhaps.

I did try adding this:

 **std::cout << ">"; getline(std::cin, command);**

here:
**https://github.com/fredimachado/IRCClient/blob/master/src/Main.cpp#L134**

but rather failed. It'd probably be great to see something like this in the future! it looks way better.

Keep the work, have a great one.

**Comment by fredimachado** [comment]
Hey Carlos,

Thanks for the suggestion, sounds like a good idea.
I guess it didn't work because that method is running in a separate thread. I'll have a look when I have some free time.

Have a great one.

Cheers!
