### ISSUE TITLE
GPLv2

### ISSUE THREAD

**Issue by legoboyvdlp** [Fredi/IRCClient#13]
Hello,

I am inquiring about the license compatibility with GPLv2.

As I understand what the FSF has said about this, referring to https://www.gnu.org/licenses/gpl-faq.html#compat-matrix-footnote-3, I'll be unable to use this client with a GPLv2 or later program unless I distribute the _combination_ under GPLv3?

I am working with a long standing project, I don't think a license change is feasible for us. What would it imply for us that the combination comes under GPL v3?

**Comment by fredimachado** [comment]
Hey,

The license here is **L**GPL-3.0: https://github.com/fredimachado/IRCClient/blob/master/COPYING

Permissions:
- Commercial use
- Modification
- Distribution
- Patent use
- Private use

I hope it helps. 👍 

Cheers,
Fredi

**Comment by legoboyvdlp** [comment]
Thanks, yep,

What I am wondering is about the ability to use this with a GPLv2 program?

**Comment by fredimachado** [comment]
I guess it should be fine, since, AFAIK LGPL is more permissive than GPL.

From https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#:~:text=The%20main%20difference%20between%20the,free%20software%20or%20proprietary%20software.

> **Differences from the GPL**
> The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is free software or proprietary software.[2] In LGPL 2.1, the non-(L)GPLed program can then be distributed under any terms if it is not a derivative work. If it is a derivative work, then the program's terms must allow for "modification of the work for the customer's own use and reverse engineering for debugging such modifications." Whether a work that uses an LGPL program is a derivative work or not is a legal issue. A standalone executable that dynamically links to a library through a .so, .dll, or similar medium is generally accepted as not being a derivative work as defined by the LGPL. It would fall under the definition of a "work that uses the Library". Paragraph 5 of the LGPL version 2.1 states:
> 
> A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.
> Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.[3]

So I guess it should be Ok, please correct me if I didn't understand the wiki page correctly.

**Comment by legoboyvdlp** [comment]
Many thanks!
