### ISSUE TITLE
gcc -Wextra

### ISSUE THREAD

**Issue by wipe2238** [Fredi/IRCClient#6]
Compiling with gcc -Wall -Wextra -Werror

> IRCClient.cpp:20:0:
> IRCHandler.h.:31:55: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
> inline int const GetCommandHandler(std::string command)

**Comment by Fredi** [comment]
Hi!

Try removing the const qualifier.

```Cpp
inline int GetCommandHandler(std::string command)
```

**Comment by wipe2238** [comment]
Yup, that fixed it :)
