### ISSUE TITLE
Expose IRCClient::_socket

### ISSUE THREAD

**Issue by wipe2238** [Fredi/IRCClient#8]
...or at least mark it as protected. If someone using repo as a tiny irc library (hey, it's me!) it allows to write own, non-blocking IRCClient::ReceiveData() without worry about possible conflicts in future.

**Comment by Fredi** [comment]
Did you manage to use it in a new thread?

**Comment by wipe2238** [comment]
Yes and no.
For test application it was working fine, but when plugged into real application other problems showed up (not IRCClient related)... [In the end](https://github.com/wipe2238/IRCClient/commit/9a5c8068fb77e87bb32ca264969bfc7b1c9bc7a7) i'm using select() for now before trying to read anything.
